version: '3.8'
services:
  postgres:
    expose:
      - "5432"
    image: postgres:latest
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: keyboardcat
    volumes:
      - "data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8000:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:keyboardcat@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: keyboardxilbe
    depends_on:
      - postgres
volumes:
  data: